### ISSUE TITLE
Support GHGC Outreach and Engagement

### ISSUE THREAD

**Issue by siddharth0248** [US-GHG-Center/ghg-hub-homepage#18]
**Motivation / Description**:

Increase community (users and stakeholders) engagement with GHGC. Collect materials for reporting to Headquarters and stakeholders, present at conferences, and develop outreach materials. 

**Success criteria**

- [ ] AMS presentation prepared 
- [ ] Prepared to provide technical support for the AMS workshop 
- [ ] Develop workshop notebooks for the activity portion 
- [ ] Prepared demonstrations, reporting slides, and documents for stakeholder meetings 
- [ ] Coordinated and hosted February MSFC meeting
- [ ] Agendas, calendar invites, materials prepared, activities planned, rooms reserved, lunch coordinated
- [ ] Drafted and distributed first US GHG Center newsletter 
- [ ] Added US GHG Center to the list of additional resources in GHG pathfinder at NASA
- [ ] Created GHGC walk through demo videos 
- [ ] Publication

**Comment by slesaad** [comment]
Objectives are added here instead - https://github.com/orgs/US-GHG-Center/projects/1

**Comment by slesaad** [comment]
Objectives are added here instead - https://github.com/orgs/US-GHG-Center/projects/1
